### ISSUE TITLE
ADD: Hybrid command system

### ISSUE THREAD

**Issue by V3ntus** [V3ntus/repo-finder-bot#9]
- ~~A core module (or write inside command module instead?) overwrites the decorator *after* the legacy command decorator gets called, and then initializes the slash command decorator. This overwrites the need for duplicate files  
https://stackoverflow.com/questions/642762/is-it-possible-to-replace-a-function-method-decorator-at-runtime-python~~

**Comment by savioxavier** [comment]
> overwrites the decorator after the legacy command decorator

I assume "legacy command decorator" refers to `@commands.command` i.e., chat commands? If that's the case, overwriting the decorator, if it's possible (I'm guessing this means changing `@commands.command` to `@cog_ext.cog_slash`) might not really work due to the fact that slash commands don't rely on chat messages and therefore, stuff like `ctx.message.author` won't work - but then again, I'm not really sure. 
Just wanted to point out the `ctx.message.author` thing in this comment, thanks.

**Comment by V3ntus** [comment]
> stuff like `ctx.message.author` won't work - but then again, I'm not really sure

Right, that's a hurdle I realized earlier. I think I've been overcomplicating the process anyways. I have something simpler and that's just calling two separate instances of the command handlers and redirecting their flow to a single function that processes the command
